# Generated by Django 3.1.2 on 2020-10-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTrigrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField(default=None, unique=True)),
                ('data_name', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Data Trigrs',
                'verbose_name_plural': 'Data Trigrs',
            },
        ),
        migrations.CreateModel(
            name='DataTrigrsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now_add=True)),
                ('ch', models.TextField(blank=True, default=None, null=True)),
                ('path_to_file', models.TextField(default=None)),
                ('trigrs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_trigrs_detail', to='trigrs.datatrigrs')),
            ],
            options={
                'verbose_name': 'Data Trigr sDetail',
                'verbose_name_plural': 'Data Trigrs Detail',
            },
        ),
    ]
