# Generated by Django 3.1.2 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatrigrsdetail',
            name='data_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
