# Generated by Django 3.1.2 on 2020-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigrs', '0002_auto_20201113_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatrigrsdetail',
            options={'verbose_name': 'Data Trigrs Detail', 'verbose_name_plural': 'Data Trigrs Detail'},
        ),
        migrations.AddField(
            model_name='datatrigrsdetail',
            name='filename',
            field=models.TextField(default=None),
        ),
    ]
