# Generated by Django 3.1.2 on 2020-11-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trigrs', '0003_auto_20201116_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatrigrsdetail',
            name='path_to_file',
        ),
    ]
